docs: Add pages for server performance-related documentation
BizKit-Tech/BizKit-Tech.github.io pull request #2
Opened 2023-08-22 09:20 UTC by gabbarbudo

Added the following pages for server performance documentation:
1. SOP for investigating performance issues
2. Performance tuning methods

2023-08-22 20:47 UTC, kevingdc approved these changes

2023-08-29 00:55 UTC, mcjraquel requested changes

2023-08-29 00:55 UTC, mcjraquel commented on content/docs/others/investigating-performance-issues/index.md
> +    - When you write print statements in your python code, the output will be displayed in the terminal window.
```suggestion
    - When you write print statements in your Python code, the output will be displayed in the terminal window.

```

2023-08-29 00:55 UTC, mcjraquel commented on content/docs/others/performance-tuning-methods.md
> +3. Then restart your mariadb service by running the following command:
```suggestion
3. Then restart your MariaDB service by running the following command:

```

2023-08-29 04:21 UTC, reddaoist approved these changes

2023-08-29 04:52 UTC, jedreyes approved these changes

2023-09-05 04:30 UTC, mcjraquel approved these changes

2023-09-06 10:54 UTC, merged