docs: Add more details to the performance investigation documentations
BizKit-Tech/BizKit-Tech.github.io pull request #6
Opened 2023-10-04 02:45 UTC by gabbarbudo

## Summary
Added the following:
- New section in Investigating Performance Issues for investigating/resolving specific cases
- New page for Logging with Frappe
- New section in Performance Tuning Methods about optimizing images for web

**Ticket Link:**
N/A

**Video/Screenshot:**
N/A

## Checklist
- [x] I have ensured that my code follows the style guidelines.
- [x] I have tested my code to ensure that it works.
- [x] I've added documentation (if necessary) to my code.

2023-10-05 08:27 UTC, kevingdc approved these changes

2023-10-06 05:25 UTC, reddaoist approved these changes

2023-10-11 01:13 UTC, mcjraquel requested changes

2023-10-11 01:13 UTC, mcjraquel commented on content/docs/others/performance-tuning-methods.md
> +- **Compression:** Compress your images to reduce file size while maintaining acceptable quality. *I* highly recommended that image file sizes be kept below 1 MB, with 100 KB being the ideal maximum
```suggestion
- **Compression:** Compress your images to reduce file size while maintaining acceptable quality. *I* highly recommend that image file sizes be kept below 1 MB, with 100 KB being the ideal maximum file size for even better performance.

```

2023-10-11 05:17 UTC, mcbsalceda approved these changes

2023-11-06 00:22 UTC, mcbsalceda approved these changes

2023-11-06 04:16 UTC, mcjraquel approved these changes

2023-11-06 06:00 UTC, merged